name: test
on: pull_request
env:
  RELEASE_VERSION: 1.0.5-alpha.0
  PREVIOUS_VERSION: 1.0.4
  STORYBOOK_BUILD: storybook-static
jobs:
  release-gh:
    runs-on: ubuntu-latest
    steps:
      - name: Set release version variable
        run: |
          version="1.0.5"
          echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
          isPreVersion=$([[ "$version" != "${version#*"-"}" ]] && echo true || echo false)
          echo "IS_PRE_VERSION=$isPreVersion" >> $GITHUB_ENV
          echo $isPreVersion
      - uses: actions/checkout@v2
      - name: Create changelog
        if: env.IS_PRE_VERSION
        id: create-changelog
        run: |
          git fetch --all --tags
          changelog=$(git log v$PREV_VERSION...v$NEW_VERSION --pretty=format:'- %s _by %aN_')
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=CHANGELOG::$changelog"
        env:
          PREV_VERSION: ${{ env.PREVIOUS_VERSION }}
          NEW_VERSION: ${{ env.RELEASE_VERSION }}
      - name: Create Github release
        id: create_release
        if: env.IS_PRE_VERSION == false
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: |
            ${{ steps.create-changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: false
